
show variables like 'TRANSACTION_ISOLATION';

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- SET GLOBAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;

-- 设置会话隔离级别
set session transaction_isolation='READ-UNCOMMITTED';